<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class BoxElementSeeder extends Seeder
{
    public function run()
    {
        DB::table('box_element')->insert([
            ["id" => "1","box_id" => "1","element_id" => "1"],
            ["id" => "2","box_id" => "3","element_id" => "1"],
            ["id" => "3","box_id" => "2","element_id" => "2"],
            ["id" => "4","box_id" => "4","element_id" => "2"],
            ["id" => "5","box_id" => "6","element_id" => "2"],
            ["id" => "6","box_id" => "5","element_id" => "3"],
            ["id" => "7","box_id" => "7","element_id" => "3"],
            ["id" => "14","box_id" => "3","element_id" => "4"],
            ["id" => "13","box_id" => "1","element_id" => "4"],
            ["id" => "10","box_id" => "2","element_id" => "5"],
            ["id" => "11","box_id" => "4","element_id" => "5"],
            ["id" => "12","box_id" => "6","element_id" => "5"],
            ["id" => "15","box_id" => "5","element_id" => "6"],
            ["id" => "16","box_id" => "7","element_id" => "6"],
            ["id" => "17","box_id" => "5","element_id" => "7"],
            ["id" => "18","box_id" => "7","element_id" => "7"],
            ["id" => "19","box_id" => "1","element_id" => "8"],
            ["id" => "20","box_id" => "2","element_id" => "8"],
            ["id" => "21","box_id" => "3","element_id" => "9"],
            ["id" => "22","box_id" => "4","element_id" => "9"],
            ["id" => "23","box_id" => "5","element_id" => "9"],
            ["id" => "24","box_id" => "6","element_id" => "9"],
            ["id" => "25","box_id" => "7","element_id" => "9"],
            ["id" => "26","box_id" => "1","element_id" => "10"],
            ["id" => "27","box_id" => "2","element_id" => "10"],
            ["id" => "28","box_id" => "3","element_id" => "11"],
            ["id" => "29","box_id" => "4","element_id" => "11"],
            ["id" => "30","box_id" => "5","element_id" => "11"],
            ["id" => "31","box_id" => "6","element_id" => "11"],
            ["id" => "32","box_id" => "7","element_id" => "11"],
            ["id" => "70","box_id" => "1","element_id" => "19"],
            ["id" => "69","box_id" => "7","element_id" => "18"],
            ["id" => "68","box_id" => "6","element_id" => "18"],
            ["id" => "67","box_id" => "5","element_id" => "18"],
            ["id" => "66","box_id" => "7","element_id" => "17"],
            ["id" => "65","box_id" => "6","element_id" => "17"],
            ["id" => "64","box_id" => "5","element_id" => "17"],
            ["id" => "77","box_id" => "1","element_id" => "20"],
            ["id" => "76","box_id" => "7","element_id" => "19"],
            ["id" => "75","box_id" => "6","element_id" => "19"],
            ["id" => "74","box_id" => "5","element_id" => "19"],
            ["id" => "73","box_id" => "4","element_id" => "19"],
            ["id" => "72","box_id" => "3","element_id" => "19"],
            ["id" => "71","box_id" => "2","element_id" => "19"],
            ["id" => "47","box_id" => "1","element_id" => "14"],
            ["id" => "48","box_id" => "2","element_id" => "14"],
            ["id" => "49","box_id" => "3","element_id" => "14"],
            ["id" => "50","box_id" => "4","element_id" => "14"],
            ["id" => "51","box_id" => "5","element_id" => "14"],
            ["id" => "52","box_id" => "6","element_id" => "14"],
            ["id" => "53","box_id" => "7","element_id" => "14"],
            ["id" => "54","box_id" => "1","element_id" => "15"],
            ["id" => "55","box_id" => "2","element_id" => "15"],
            ["id" => "56","box_id" => "3","element_id" => "15"],
            ["id" => "57","box_id" => "4","element_id" => "15"],
            ["id" => "58","box_id" => "5","element_id" => "15"],
            ["id" => "59","box_id" => "6","element_id" => "15"],
            ["id" => "60","box_id" => "7","element_id" => "15"],
            ["id" => "78","box_id" => "2","element_id" => "20"],
            ["id" => "79","box_id" => "3","element_id" => "20"],
            ["id" => "80","box_id" => "4","element_id" => "20"],
            ["id" => "81","box_id" => "5","element_id" => "20"],
            ["id" => "82","box_id" => "6","element_id" => "20"],
            ["id" => "83","box_id" => "7","element_id" => "20"],
            ["id" => "84","box_id" => "1","element_id" => "21"],
            ["id" => "85","box_id" => "2","element_id" => "21"],
            ["id" => "86","box_id" => "3","element_id" => "21"],
            ["id" => "87","box_id" => "4","element_id" => "21"],
            ["id" => "88","box_id" => "5","element_id" => "21"],
            ["id" => "89","box_id" => "6","element_id" => "21"],
            ["id" => "90","box_id" => "7","element_id" => "21"],
            ["id" => "91","box_id" => "1","element_id" => "22"],
            ["id" => "92","box_id" => "2","element_id" => "22"],
            ["id" => "93","box_id" => "3","element_id" => "22"],
            ["id" => "94","box_id" => "4","element_id" => "22"],
            ["id" => "95","box_id" => "5","element_id" => "22"],
            ["id" => "96","box_id" => "6","element_id" => "22"],
            ["id" => "97","box_id" => "7","element_id" => "22"],
            ["id" => "98","box_id" => "1","element_id" => "23"],
            ["id" => "99","box_id" => "2","element_id" => "23"],
            ["id" => "100","box_id" => "3","element_id" => "23"],
            ["id" => "101","box_id" => "4","element_id" => "23"],
            ["id" => "102","box_id" => "5","element_id" => "23"],
            ["id" => "103","box_id" => "6","element_id" => "23"],
            ["id" => "104","box_id" => "7","element_id" => "23"]
        ]);
    }
}
